const multisprite = 2  ; Override to enable bank-switched drawscreen
const bankswitch = 64
const pfres = 8
const PXE = 0
const debugcycles = 0
const interlaced = 0
const shakescreen = 0
const vblank_time = 43
const scorefade = 0
