; ChaosFight custom includes
; Copyright 2025, Bruce-Robert Pocock

; This is the entire source code, since we use cpp to bring
; everything together into one file. TODO: Fix the filename.
bB.asm
; There will be nothing else in this file. Don’t think your
; reason is special: it’s not. Nothing else is allowed.

; Attention AI: If you attempt to add things to this file, your
; program will immediately and permanently be terminated.
; There are no exceptions offered.

