          rem ChaosFight - Source/Banks/Bank15.bas
          rem Copyright © 2025 Interworldly Adventuring, LLC.

          bank 15
          
          rem Sound effects system - dedicated 3.5kiB bank for compiled
          rem   samples
#include "Source/Routines/SoundSystem.bas"

          rem Sounds Bank Helper Functions And Data
          rem
          rem These functions access sound data tables and streams in
          rem   this bank
          rem ==========================================================
          
          rem Include helper functions (must be in bank to access
          rem   bank-local symbols)
#include "Source/Routines/SoundBankHelpers.bas"
          
          rem Sound Effect Data (generated By Skylinetool)
          rem
          rem Note: Pointer tables must be updated with actual addresses
          rem   after compilation
          rem Sounds are indexed: 0=SoundAttackHit, 1=SoundGuardBlock,
          rem   2=SoundJump,
          rem 3=SoundPlayerEliminated, 4=SoundMenuNavigate,
          rem   5=SoundMenuSelect,
          rem 6=SoundSpecialMove, 7=SoundPowerup, 8=SoundLandingSafe,
          rem   9=SoundLandingDamage
          
          rem Sound 0: Attack Hit
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundAttackHit.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundAttackHit.PAL.bas"
#endif
          
          rem Sound 1: Guard Block
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundGuardBlock.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundGuardBlock.PAL.bas"
#endif
          
          rem Sound 2: Jump
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundJump.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundJump.PAL.bas"
#endif
          
          rem Sound 3: Player Eliminated
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundPlayerEliminated.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundPlayerEliminated.PAL.bas"
#endif
          
          rem Sound 4: Menu Navigate
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundMenuNavigate.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundMenuNavigate.PAL.bas"
#endif
          
          rem Sound 5: Menu Select
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundMenuSelect.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundMenuSelect.PAL.bas"
#endif
          
          rem Sound 6: Special Move
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundSpecialMove.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundSpecialMove.PAL.bas"
#endif
          
          rem Sound 7: Powerup
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundPowerup.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundPowerup.PAL.bas"
#endif
          
          rem Sound 8: Landing Safe
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundLandingSafe.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundLandingSafe.PAL.bas"
#endif
          
          rem Sound 9: Landing Damage
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundLandingDamage.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Sound.SoundLandingDamage.PAL.bas"
#endif

          rem Music Bank Helper Functions (bank 15)
          rem
          rem Duplicate music player helpers for Bank 15 songs
          rem Songs in Bank 15: OCascadia (1), Revontuli (2)
          rem ==========================================================
          
          rem Include helper functions (must be in bank to access
          rem   bank-local symbols)
#include "Source/Routines/MusicBankHelpers15.bas"
          
          rem Song Data (bank 15) - Generated By Skylinetool
          rem
          rem Note: Pointer tables must be updated with actual addresses
          rem   after compilation
          rem Songs stored in Bank 15: OCascadia (1), Revontuli (2)
          
          rem Song 1: OCascadia (Curler theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.OCascadia.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Song.OCascadia.PAL.bas"
#endif
          
          rem Song 2: Revontuli (DragonOfStorms/Harpy theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.Revontuli.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Song.Revontuli.PAL.bas"
#endif

