;;; ChaosFight - Source/Banks/Bank14.s
;;;Copyright © 2025 Bruce-Robert Pocock.

;;;ASSET BANK: Music/Sound Assets (separate memory budget)
;;;Sound effects + character theme songs (IDs 0-6): Bernie, OCascadia,
          ;; Revontuli, EXO, Grizzards, MagicalFairyForce, Bolero

          ;; Set file offset for Bank 14 at the top of the file
          .offs (14 * $1000) - $f000  ; Adjust file offset for Bank 14
          * = $F000
          .rept 256
          .byte $ff
          .endrept  ;; Scram shadow (256 bytes of $FF)
          * = $F100

          ;; SOUND BANK 2 --- NOTHING but sounds & music are allowed here.

          ;; Song Data (bank 15) - Generated By Skylinetool
          ;; Note: Pointer tables must be updated with actual addresses
          ;; after compilation
          ;; Songs stored in Bank 14: IDs 0-Bank14MaxSongID (currently Bernie, OCascadia, Revontuli, EXO, Grizzards, MagicalFairyForce, Bolero)

Bank15DataStart:
BernieSongStart:

          ;; Song 0: Bernie (Bernie’s theme)
.if TVStandard == 0
.include "Source/Generated/Song.Bernie.NTSC.s"
.else
.include "Source/Generated/Song.Bernie.PAL.s"
.fi
BernieSongEnd:
            .warn format("// Bank 14: %d bytes = Song.Bernie", [BernieSongEnd - BernieSongStart])
OCascadiaSongStart:

          ;; Song 1: OCascadia (Curler theme)
.if TVStandard == 0
.include "Source/Generated/Song.OCascadia.NTSC.s"
.else
.include "Source/Generated/Song.OCascadia.PAL.s"
.fi
OCascadiaSongEnd:
            .warn format("// Bank 14: %d bytes = Song.OCascadia", [OCascadiaSongEnd - OCascadiaSongStart])
RevontuliSongStart:

          ;; Song 2: Revontuli (Dragon of Storms/Harpy theme)
.if TVStandard == 0
.include "Source/Generated/Song.Revontuli.NTSC.s"
.else
.include "Source/Generated/Song.Revontuli.PAL.s"
.fi
RevontuliSongEnd:
            .warn format("// Bank 14: %d bytes = Song.Revontuli", [RevontuliSongEnd - RevontuliSongStart])
EXOSongStart:

          ;; Song 3: EXO (Zoe Ryen theme)
.if TVStandard == 0
.include "Source/Generated/Song.EXO.NTSC.s"
.else
.include "Source/Generated/Song.EXO.PAL.s"
.fi
EXOSongEnd:
            .warn format("// Bank 14: %d bytes = Song.EXO", [EXOSongEnd - EXOSongStart])
MagicalFairyForceSongStart:

          ;; Song 5: MagicalFairyForce (shared character theme)
.if TVStandard == 0
.include "Source/Generated/Song.MagicalFairyForce.NTSC.s"
.else
.include "Source/Generated/Song.MagicalFairyForce.PAL.s"
.fi
MagicalFairyForceSongEnd:
            .warn format("// Bank 14: %d bytes = Song.MagicalFairyForce", [MagicalFairyForceSongEnd - MagicalFairyForceSongStart])
GrizzardsSongStart:

          ;; Song 4: Grizzards (shared theme across characters)
.if TVStandard == 0
.include "Source/Generated/Song.Grizzards.NTSC.s"
.else
.include "Source/Generated/Song.Grizzards.PAL.s"
.fi
GrizzardsSongEnd:
            .warn format("// Bank 14: %d bytes = Song.Grizzards", [GrizzardsSongEnd - GrizzardsSongStart])
BoleroSongStart:

          ;; Song 6: Bolero (shared theme across characters)
.if TVStandard == 0
.include "Source/Generated/Song.Bolero.NTSC.s"
.else
.include "Source/Generated/Song.Bolero.PAL.s"
.fi
BoleroSongEnd:
            .warn format("// Bank 14: %d bytes = Song.Bolero", [BoleroSongEnd - BoleroSongStart])
SoundAttackHitStart:

          ;; Sound Effect Data (generated By Skylinetool)

          ;; Sound 0: Attack Hit
.if TVStandard == 0
.include "Source/Generated/Sound.SoundAttackHit.NTSC.s"
.else
.include "Source/Generated/Sound.SoundAttackHit.PAL.s"
.fi
SoundAttackHitEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundAttackHit", [SoundAttackHitEnd - SoundAttackHitStart])
SoundGuardBlockStart:

          ;; Sound 1: Guard Block
.if TVStandard == 0
.include "Source/Generated/Sound.SoundGuardBlock.NTSC.s"
.else
.include "Source/Generated/Sound.SoundGuardBlock.PAL.s"
.fi
SoundGuardBlockEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundGuardBlock", [SoundGuardBlockEnd - SoundGuardBlockStart])
SoundJumpStart:

          ;; Sound 2: Jump
.if TVStandard == 0
.include "Source/Generated/Sound.SoundJump.NTSC.s"
.else
.include "Source/Generated/Sound.SoundJump.PAL.s"
.fi
SoundJumpEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundJump", [SoundJumpEnd - SoundJumpStart])
SoundPlayerEliminatedStart:

          ;; Sound 3: Player Eliminated
.if TVStandard == 0
.include "Source/Generated/Sound.SoundPlayerEliminated.NTSC.s"
.else
.include "Source/Generated/Sound.SoundPlayerEliminated.PAL.s"
.fi
SoundPlayerEliminatedEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundPlayerEliminated", [SoundPlayerEliminatedEnd - SoundPlayerEliminatedStart])
SoundMenuNavigateStart:

          ;; Sound 4: Menu Navigate
.if TVStandard == 0
.include "Source/Generated/Sound.SoundMenuNavigate.NTSC.s"
.else
.include "Source/Generated/Sound.SoundMenuNavigate.PAL.s"
.fi
SoundMenuNavigateEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundMenuNavigate", [SoundMenuNavigateEnd - SoundMenuNavigateStart])
SoundMenuSelectStart:

          ;; Sound 5: Menu Select
.if TVStandard == 0
.include "Source/Generated/Sound.SoundMenuSelect.NTSC.s"
.else
.include "Source/Generated/Sound.SoundMenuSelect.PAL.s"
.fi
SoundMenuSelectEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundMenuSelect", [SoundMenuSelectEnd - SoundMenuSelectStart])
SoundSpecialMoveStart:

          ;; Sound 6: Special Move
.if TVStandard == 0
.include "Source/Generated/Sound.SoundSpecialMove.NTSC.s"
.else
.include "Source/Generated/Sound.SoundSpecialMove.PAL.s"
.fi
SoundSpecialMoveEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundSpecialMove", [SoundSpecialMoveEnd - SoundSpecialMoveStart])
SoundPowerupStart:

          ;; Sound 7: Powerup
.if TVStandard == 0
.include "Source/Generated/Sound.SoundPowerup.NTSC.s"
.else
.include "Source/Generated/Sound.SoundPowerup.PAL.s"
.fi
SoundPowerupEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundPowerup", [SoundPowerupEnd - SoundPowerupStart])
SoundLandingSafeStart:

          ;; Sound 8: Landing Safe
.if TVStandard == 0
.include "Source/Generated/Sound.SoundLandingSafe.NTSC.s"
.else
.include "Source/Generated/Sound.SoundLandingSafe.PAL.s"
.fi
SoundLandingSafeEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundLandingSafe", [SoundLandingSafeEnd - SoundLandingSafeStart])
SoundLandingDamageStart:

          ;; Sound 9: Landing Damage
.if TVStandard == 0
.include "Source/Generated/Sound.SoundLandingDamage.NTSC.s"
.else
.include "Source/Generated/Sound.SoundLandingDamage.PAL.s"
.fi
SoundLandingDamageEnd:
            .warn format("// Bank 14: %d bytes = Sound.SoundLandingDamage", [SoundLandingDamageEnd - SoundLandingDamageStart])
SoundPointersStart:

          ;; Data segment for sound and song pointer tables
.include "Source/Data/SoundPointers.s"
SoundPointersEnd:
            .warn format("// Bank 14: %d bytes = SoundPointers", [SoundPointersEnd - SoundPointersStart])
SongPointers2Start:
.include "Source/Data/SongPointers2.s"
SongPointers2End:
            .warn format("// Bank 14: %d bytes = SongPointers2", [SongPointers2End - SongPointers2Start])
Bank14DataEnds:

          ;; Sounds Bank Helper Functions And Data
LoadSoundPointerStart:
.include "Source/Routines/LoadSoundPointer.s"
LoadSoundPointerEnd:
            .warn format("// Bank 14: %d bytes = LoadSoundPointer", [LoadSoundPointerEnd - LoadSoundPointerStart])
LoadSoundNoteStart:
.include "Source/Routines/LoadSoundNote.s"
LoadSoundNoteEnd:
            .warn format("// Bank 14: %d bytes = LoadSoundNote", [LoadSoundNoteEnd - LoadSoundNoteStart])
LoadSoundNote1Start:
.include "Source/Routines/LoadSoundNote1.s"
LoadSoundNote1End:
            .warn format("// Bank 14: %d bytes = LoadSoundNote1", [LoadSoundNote1End - LoadSoundNote1Start])
UpdateSoundEffectVoice0Start:
.include "Source/Routines/UpdateSoundEffectVoice0.s"
UpdateSoundEffectVoice0End:
            .warn format("// Bank 14: %d bytes = UpdateSoundEffectVoice0", [UpdateSoundEffectVoice0End - UpdateSoundEffectVoice0Start])
UpdateSoundEffectVoice1Start:
.include "Source/Routines/UpdateSoundEffectVoice1.s"
UpdateSoundEffectVoice1End:
            .warn format("// Bank 14: %d bytes = UpdateSoundEffectVoice1", [UpdateSoundEffectVoice1End - UpdateSoundEffectVoice1Start])
PlaySoundEffectStart:
.include "Source/Routines/PlaySoundEffect.s"
PlaySoundEffectEnd:
            .warn format("// Bank 14: %d bytes = PlaySoundEffect", [PlaySoundEffectEnd - PlaySoundEffectStart])
UpdateSoundEffectStart:
.include "Source/Routines/UpdateSoundEffect.s"
UpdateSoundEffectEnd:
            .warn format("// Bank 14: %d bytes = UpdateSoundEffect", [UpdateSoundEffectEnd - UpdateSoundEffectStart])
StopSoundEffectsStart:
.include "Source/Routines/StopSoundEffects.s"
StopSoundEffectsEnd:
            .warn format("// Bank 14: %d bytes = StopSoundEffects", [StopSoundEffectsEnd - StopSoundEffectsStart])
MusicBankHelpers15Start:
.include "Source/Routines/MusicBankHelpers15.s"
MusicBankHelpers15End:
            .warn format("// Bank 14: %d bytes = MusicBankHelpers15", [MusicBankHelpers15End - MusicBankHelpers15Start])
MusicSystemStart:
.include "Source/Routines/MusicSystem.s"
MusicSystemEnd:
            .warn format("// Bank 14: %d bytes = MusicSystem", [MusicSystemEnd - MusicSystemStart])
Bank14CodeEnds:

          ;; Include BankSwitching.s in Bank 14
          ;; Wrap in .block to create namespace Bank14BS (avoids duplicate definitions)
Bank14BS: .block
          current_bank = 14
                    ;; Set file offset and CPU address for bankswitch code
          ;; File offset: (14 * $1000) + ($FFE0 - bscode_length - $F000) = $14FC8
          ;; CPU address: $FFE0 - bscode_length = $FFC8
          ;; Use .org to set file offset, then * = to set CPU address
          ;; Code appears at $ECA but should be at $FC8, difference is $FE
          ;; So adjust .org by $FE
          * = $FFE0 - bscode_length
          
          
          .include "Source/Common/BankSwitching.s"
          .bend
