          rem ChaosFight - Source/Banks/Bank16.bas
          rem Copyright © 2025 Interworldly Adventuring, LLC.

          bank 16
          
#include "Source/Data/SongPointers16.bas"
          
          rem
          rem Song Data (bank 16) - Generated By Skylinetool
          rem Note: Pointer tables must be updated with actual addresses
          rem   after compilation
          rem
          rem Songs stored in Bank 16: All songs except OCascadia (1)
          rem and
          rem   Revontuli (2) which are in Bank 15
          rem Songs 0, 3-28 are in this bank
          
          rem Temporary Workaround: Character Theme Songs Commented Out
          rem
          rem ISSUE: Character theme music files are too large for Bank
          rem 16
          rem   ROM space. This is causing build failures due to bank
          rem   overflow.
          rem
          rem STATUS: This is a temporary workaround authorized one-time
          rem to
          rem   unbreak the build. Character theme songs (Song IDs 0,
          rem   3-25) are
          rem   commented out until proper ROM distribution can be
          rem   implemented.
          rem
          rem IMPACT: 
          rem   - Character themes will not play during gameplay
          rem   - Music system will return null pointers for character
          rem   songs
          rem   - Admin screen songs (Chaotica, AtariToday,
          rem   Interworldly) remain
          rem     active and functional
          rem NEXT STEPS (when resuming this work):
          rem
          rem   1. Analyze ROM distribution across all 16 banks
          rem   2. Redistribute character themes to fit within available
          rem   space
          rem   3. Consider compressing or optimizing song data
          rem   4. May need to split character themes across multiple
          rem   banks
          rem   5. Update pointer tables after distribution changes
          rem AFFECTED SONGS (commented out):
          rem   Song 0: Bernie (Character 0 theme)
          rem   Song 3: EXO (Character 3 - ZoeRyen theme)
          rem   Song 4: Grizzards (Character 4 - FatTony theme)
          rem   Song 5: MagicalFairyForce (Character 7 - KnightGuy
          rem   theme)
          rem   Song 6: Bolero (Character 9 - Nefertem theme)
          rem   Song 7: LowRes (Character 10 - NinjishGuy theme)
          rem   Song 8: RoboTito (Character 13 theme)
          rem   Song 9: SongOfTheBear (Character 14 - Ursulo theme)
          rem   Song 10: DucksAway (Character 15 - Shamone theme)
          rem   Songs 11-25: Character16Theme through Character30Theme
          
          rem Song 0: Bernie (Character 0 theme) - COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.Bernie.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.Bernie.PAL.bas"
          rem #endif
          
          rem Song 3: EXO (Character 3 - ZoeRyen theme) - COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.EXO.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.EXO.PAL.bas"
          rem #endif
          
          rem Song 4: Grizzards (Character 4 - FatTony theme) -
          rem COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.Grizzards.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.Grizzards.PAL.bas"
          rem #endif
          
          rem Song 5: MagicalFairyForce (Character 7 - KnightGuy theme)
          rem - COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include
          rem "Source/Generated/Song.MagicalFairyForce.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.MagicalFairyForce.PAL.bas"
          rem #endif
          
          rem Song 6: Bolero (Character 9 - Nefertem theme) - COMMENTED
          rem OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.Bolero.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.Bolero.PAL.bas"
          rem #endif
          
          rem Song 7: LowRes (Character 10 - NinjishGuy theme) -
          rem COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.LowRes.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.LowRes.PAL.bas"
          rem #endif
          
          rem Song 8: RoboTito (Character 13 theme) - COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.RoboTito.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.RoboTito.PAL.bas"
          rem #endif
          
          rem Song 9: SongOfTheBear (Character 14 - Ursulo theme) -
          rem COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.SongOfTheBear.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.SongOfTheBear.PAL.bas"
          rem #endif
          
          rem Song 10: DucksAway (Character 15 - Shamone theme) -
          rem COMMENTED OUT
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.DucksAway.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.DucksAway.PAL.bas"
          rem #endif
          
          rem Songs 11-25: Character16Theme through Character30Theme -
          rem COMMENTED OUT
          rem   (Placeholder themes for future characters)
          rem #ifdef TV_NTSC
          rem #include "Source/Generated/Song.Character16Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character17Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character18Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character19Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character20Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character21Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character22Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character23Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character24Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character25Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character26Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character27Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character28Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character29Theme.NTSC.bas"
          rem #include "Source/Generated/Song.Character30Theme.NTSC.bas"
          rem #else
          rem   rem PAL or SECAM: Use PAL version for both
          rem #include "Source/Generated/Song.Character16Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character17Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character18Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character19Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character20Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character21Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character22Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character23Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character24Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character25Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character26Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character27Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character28Theme.PAL.bas"
          rem
          rem #include "Source/Generated/Song.Character29Theme.PAL.bas"
          rem #include "Source/Generated/Song.Character30Theme.PAL.bas"
          rem #endif
          
          rem Admin Screen Songs (song Ids 26-28)
          
          rem Song 26: Chaotica (Title screen - loops)
#ifdef TV_NTSC
#include "Source/Generated/Song.Chaotica.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Song.Chaotica.PAL.bas"
#endif
          
          rem Song 27: AtariToday (Publisher prelude)
#ifdef TV_NTSC
#include "Source/Generated/Song.AtariToday.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Song.AtariToday.PAL.bas"
#endif
          
          rem Song 28: Interworldly (Author prelude)
#ifdef TV_NTSC
#include "Source/Generated/Song.Interworldly.NTSC.bas"
#else
          rem PAL or SECAM: Use PAL version for both
#include "Source/Generated/Song.Interworldly.PAL.bas"
#endif
          
         rem
         rem Music System Code (must follow data)
         rem Music system - dedicated 3.5kiB bank for compiled samples
#include "Source/Routines/MusicSystem.bas"
         
         rem Songs bank helper functions (require bank-local symbols)
#include "Source/Routines/MusicBankHelpers.bas"
          
          rem
          rem Build Info - Version Tracking And Attribution
          rem Build date in year.julian format (e.g., 2025.256)
          rem Game URL: https://interworldly.com/games/ChaosFight
          rem These strings are embedded in the ROM after the end of
          rem   real code
          rem Note: Strings are defined in BuildInfo.s and included with
          rem   bare "include" directive (not #include) to avoid C
          rem   preprocessor
          rem   quote issues
          
          asm
          include "Source/Common/BuildInfo.s"
end
