          rem ChaosFight - Source/Banks/Bank15.bas
          rem Copyright © 2025 Interworldly Adventuring, LLC.
          rem
          rem ASSET BANK: Music/Sound Assets (separate memory budget)
          rem Sound effects + character theme songs (IDs 0-6): Bernie, OCascadia,
          rem   Revontuli, EXO, Grizzards, MagicalFairyForce, Bolero

          bank 15

          rem SOUND BANK 2 --- NOTHING but sounds & music are allowed here.

          rem Song Data (bank 15) - Generated By Skylinetool
          rem Note: Pointer tables must be updated with actual addresses
          rem   after compilation
          rem Songs stored in Bank 15: IDs 0-Bank15MaxSongID (currently Bernie, OCascadia, Revontuli, EXO, Grizzards, MagicalFairyForce, Bolero)

          asm
Bank15DataStart
BernieSongStart
end

          rem Song 0: Bernie (Bernie’s theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.Bernie.NTSC.bas"
#else
#include "Source/Generated/Song.Bernie.PAL.bas"
#endif
          asm
BernieSongEnd
            echo "// Bank 15: ", [BernieSongEnd - BernieSongStart]d, " bytes = Song.Bernie"
OCascadiaSongStart
end

          rem Song 1: OCascadia (Curler theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.OCascadia.NTSC.bas"
#else
#include "Source/Generated/Song.OCascadia.PAL.bas"
#endif
          asm
OCascadiaSongEnd
            echo "// Bank 15: ", [OCascadiaSongEnd - OCascadiaSongStart]d, " bytes = Song.OCascadia"
RevontuliSongStart
end

          rem Song 2: Revontuli (Dragon of Storms/Harpy theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.Revontuli.NTSC.bas"
#else
#include "Source/Generated/Song.Revontuli.PAL.bas"
#endif
          asm
RevontuliSongEnd
            echo "// Bank 15: ", [RevontuliSongEnd - RevontuliSongStart]d, " bytes = Song.Revontuli"
EXOSongStart
end

          rem Song 3: EXO (Zoe Ryen theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.EXO.NTSC.bas"
#else
#include "Source/Generated/Song.EXO.PAL.bas"
#endif
          asm
EXOSongEnd
            echo "// Bank 15: ", [EXOSongEnd - EXOSongStart]d, " bytes = Song.EXO"
MagicalFairyForceSongStart
end

          rem Song 5: MagicalFairyForce (shared character theme)
#ifdef TV_NTSC
#include "Source/Generated/Song.MagicalFairyForce.NTSC.bas"
#else
#include "Source/Generated/Song.MagicalFairyForce.PAL.bas"
#endif
          asm
MagicalFairyForceSongEnd
            echo "// Bank 15: ", [MagicalFairyForceSongEnd - MagicalFairyForceSongStart]d, " bytes = Song.MagicalFairyForce"
GrizzardsSongStart
end

          rem Song 4: Grizzards (shared theme across characters)
#ifdef TV_NTSC
#include "Source/Generated/Song.Grizzards.NTSC.bas"
#else
#include "Source/Generated/Song.Grizzards.PAL.bas"
#endif
          asm
GrizzardsSongEnd
            echo "// Bank 15: ", [GrizzardsSongEnd - GrizzardsSongStart]d, " bytes = Song.Grizzards"
BoleroSongStart
end

          rem Song 6: Bolero (shared theme across characters)
#ifdef TV_NTSC
#include "Source/Generated/Song.Bolero.NTSC.bas"
#else
#include "Source/Generated/Song.Bolero.PAL.bas"
#endif
          asm
BoleroSongEnd
            echo "// Bank 15: ", [BoleroSongEnd - BoleroSongStart]d, " bytes = Song.Bolero"
SoundAttackHitStart
end

          rem Sound Effect Data (generated By Skylinetool)

          rem Sound 0: Attack Hit
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundAttackHit.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundAttackHit.PAL.bas"
#endif
          asm
SoundAttackHitEnd
            echo "// Bank 15: ", [SoundAttackHitEnd - SoundAttackHitStart]d, " bytes = Sound.SoundAttackHit"
SoundGuardBlockStart
end

          rem Sound 1: Guard Block
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundGuardBlock.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundGuardBlock.PAL.bas"
#endif
          asm
SoundGuardBlockEnd
            echo "// Bank 15: ", [SoundGuardBlockEnd - SoundGuardBlockStart]d, " bytes = Sound.SoundGuardBlock"
SoundJumpStart
end

          rem Sound 2: Jump
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundJump.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundJump.PAL.bas"
#endif
          asm
SoundJumpEnd
            echo "// Bank 15: ", [SoundJumpEnd - SoundJumpStart]d, " bytes = Sound.SoundJump"
SoundPlayerEliminatedStart
end

          rem Sound 3: Player Eliminated
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundPlayerEliminated.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundPlayerEliminated.PAL.bas"
#endif
          asm
SoundPlayerEliminatedEnd
            echo "// Bank 15: ", [SoundPlayerEliminatedEnd - SoundPlayerEliminatedStart]d, " bytes = Sound.SoundPlayerEliminated"
SoundMenuNavigateStart
end

          rem Sound 4: Menu Navigate
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundMenuNavigate.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundMenuNavigate.PAL.bas"
#endif
          asm
SoundMenuNavigateEnd
            echo "// Bank 15: ", [SoundMenuNavigateEnd - SoundMenuNavigateStart]d, " bytes = Sound.SoundMenuNavigate"
SoundMenuSelectStart
end

          rem Sound 5: Menu Select
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundMenuSelect.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundMenuSelect.PAL.bas"
#endif
          asm
SoundMenuSelectEnd
            echo "// Bank 15: ", [SoundMenuSelectEnd - SoundMenuSelectStart]d, " bytes = Sound.SoundMenuSelect"
SoundSpecialMoveStart
end

          rem Sound 6: Special Move
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundSpecialMove.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundSpecialMove.PAL.bas"
#endif
          asm
SoundSpecialMoveEnd
            echo "// Bank 15: ", [SoundSpecialMoveEnd - SoundSpecialMoveStart]d, " bytes = Sound.SoundSpecialMove"
SoundPowerupStart
end

          rem Sound 7: Powerup
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundPowerup.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundPowerup.PAL.bas"
#endif
          asm
SoundPowerupEnd
            echo "// Bank 15: ", [SoundPowerupEnd - SoundPowerupStart]d, " bytes = Sound.SoundPowerup"
SoundLandingSafeStart
end

          rem Sound 8: Landing Safe
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundLandingSafe.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundLandingSafe.PAL.bas"
#endif
          asm
SoundLandingSafeEnd
            echo "// Bank 15: ", [SoundLandingSafeEnd - SoundLandingSafeStart]d, " bytes = Sound.SoundLandingSafe"
SoundLandingDamageStart
end

          rem Sound 9: Landing Damage
#ifdef TV_NTSC
#include "Source/Generated/Sound.SoundLandingDamage.NTSC.bas"
#else
#include "Source/Generated/Sound.SoundLandingDamage.PAL.bas"
#endif
          asm
SoundLandingDamageEnd
            echo "// Bank 15: ", [SoundLandingDamageEnd - SoundLandingDamageStart]d, " bytes = Sound.SoundLandingDamage"
SoundPointersStart
end

          rem
          rem Data segment for sound and song pointer tables
#include "Source/Data/SoundPointers.bas"
          asm
SoundPointersEnd
            echo "// Bank 15: ", [SoundPointersEnd - SoundPointersStart]d, " bytes = SoundPointers"
SongPointers2Start
end
#include "Source/Data/SongPointers2.bas"
          asm
SongPointers2End
            echo "// Bank 15: ", [SongPointers2End - SongPointers2Start]d, " bytes = SongPointers2"
Bank15DataEnds
end

          rem Sounds Bank Helper Functions And Data
          asm
LoadSoundPointerStart
end
#include "Source/Routines/LoadSoundPointer.bas"
          asm
LoadSoundPointerEnd
            echo "// Bank 15: ", [LoadSoundPointerEnd - LoadSoundPointerStart]d, " bytes = LoadSoundPointer"
LoadSoundNoteStart
end
#include "Source/Routines/LoadSoundNote.bas"
          asm
LoadSoundNoteEnd
            echo "// Bank 15: ", [LoadSoundNoteEnd - LoadSoundNoteStart]d, " bytes = LoadSoundNote"
LoadSoundNote1Start
end
#include "Source/Routines/LoadSoundNote1.bas"
          asm
LoadSoundNote1End
            echo "// Bank 15: ", [LoadSoundNote1End - LoadSoundNote1Start]d, " bytes = LoadSoundNote1"
UpdateSoundEffectVoice0Start
end
#include "Source/Routines/UpdateSoundEffectVoice0.bas"
          asm
UpdateSoundEffectVoice0End
            echo "// Bank 15: ", [UpdateSoundEffectVoice0End - UpdateSoundEffectVoice0Start]d, " bytes = UpdateSoundEffectVoice0"
UpdateSoundEffectVoice1Start
end
#include "Source/Routines/UpdateSoundEffectVoice1.bas"
          asm
UpdateSoundEffectVoice1End
            echo "// Bank 15: ", [UpdateSoundEffectVoice1End - UpdateSoundEffectVoice1Start]d, " bytes = UpdateSoundEffectVoice1"
PlaySoundEffectStart
end
#include "Source/Routines/PlaySoundEffect.bas"
          asm
PlaySoundEffectEnd
            echo "// Bank 15: ", [PlaySoundEffectEnd - PlaySoundEffectStart]d, " bytes = PlaySoundEffect"
UpdateSoundEffectStart
end
#include "Source/Routines/UpdateSoundEffect.bas"
          asm
UpdateSoundEffectEnd
            echo "// Bank 15: ", [UpdateSoundEffectEnd - UpdateSoundEffectStart]d, " bytes = UpdateSoundEffect"
StopSoundEffectsStart
end
#include "Source/Routines/StopSoundEffects.bas"
          asm
StopSoundEffectsEnd
            echo "// Bank 15: ", [StopSoundEffectsEnd - StopSoundEffectsStart]d, " bytes = StopSoundEffects"
MusicBankHelpers15Start
end
#include "Source/Routines/MusicBankHelpers15.bas"
          asm
MusicBankHelpers15End
            echo "// Bank 15: ", [MusicBankHelpers15End - MusicBankHelpers15Start]d, " bytes = MusicBankHelpers15"
MusicSystemStart
end
#include "Source/Routines/MusicSystem.bas"
          asm
MusicSystemEnd
            echo "// Bank 15: ", [MusicSystemEnd - MusicSystemStart]d, " bytes = MusicSystem"
Bank15CodeEnds
end
