          rem ChaosFight - Source/Routines/MainLoop.bas
          rem Copyright © 2025 Bruce-Robert Pocock.

MainLoop
          rem Returns: Far (return otherbank)
          asm
MainLoop
end
          rem Dispatches game modes and handles reset entry point
          rem Returns: Far (return otherbank)
          rem Inputs: switchreset (hardware), gameMode (global 0-7)
          rem Outputs: Dispatches to mode-specific handlers
          rem Mutates: None; dispatcher only
          rem Calls: WarmStart bank13, PublisherPreludeMain bank14, AuthorPrelude bank14,
          rem        TitleScreenMain bank14, CharacterSelectInputEntry bank9,
          rem        FallingAnimation1 bank11, ArenaSelect1 bank14,
          rem        GameMainLoop bank11, WinnerAnnouncementLoop bank12,
          rem        PlayMusic bank1, titledrawscreen bank9
          rem Constraints: Must remain colocated with MainLoopDrawScreen

          rem Entry point for entire game loop
          rem Increment frame counter (used for frame budgeting and timing)
          let frame = frame + 1
          if switchreset then gosub WarmStart bank13
          ; fall through to continue

          rem Optimized: Use on/gosub for space efficiency
          rem on gameMode gosub uses RTS to jump to target, returns to ongosub0 (generated by batariBASIC)
          on gameMode gosub MainLoopModePublisherPrelude MainLoopModeAuthorPrelude MainLoopModeTitleScreen MainLoopModeCharacterSelect MainLoopModeFallingAnimation MainLoopModeArenaSelect MainLoopModeGameMain MainLoopModeWinnerAnnouncement
          ; Execution continues at ongosub0 label (generated by batariBASIC after jump tables)
          ; Mode handlers return otherbank here after completing
          ; CRITICAL FIX: ongosub0 is at same address as MainLoopModePublisherPrelude, causing fall-through
          ; We need to add explicit jump here to prevent fall-through into handlers
          ; This will be placed at ongosub0 by the assembler
          goto MainLoopContinue

MainLoopModePublisherPrelude
          rem CRITICAL: on gameMode gosub now pushes return otherbank address first, then JMPs to target
          rem Returns: Far (return otherbank)
          rem So when MainLoopModePublisherPrelude starts, the stack has 2 bytes (return otherbank to ongosub0)
          rem gosub PublisherPreludeMain bank14 is a far call (pushes 4-byte encoded return otherbank)
          rem When PublisherPreludeMain returns with return otherbank, it pops 2 bytes from the encoded return otherbank address
          rem This leaves the 2-byte return otherbank address from on gameMode gosub on the stack
          rem So we must use return otherbank (RTS) to pop that 2-byte address
          gosub PublisherPreludeMain bank14
          return otherbank
MainLoopModeAuthorPrelude
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub AuthorPrelude bank14
          return otherbank
MainLoopModeTitleScreen
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub TitleScreenMain bank14
          return otherbank
MainLoopModeCharacterSelect
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub CharacterSelectInputEntry bank9
          return otherbank
MainLoopModeFallingAnimation
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub FallingAnimation1 bank11
          return otherbank
MainLoopModeArenaSelect
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub ArenaSelect1 bank14
          return otherbank
MainLoopModeGameMain
          rem CRITICAL: Guard against being called when not in game mode
          rem Returns: Far (return otherbank)
          rem This prevents crashes when gameMode is corrupted or incorrectly set
          rem Only call GameMainLoop when actually in game mode (ModeGame = 6)
          if gameMode = ModeGame then goto MainLoopModeGameMainContinue
          return otherbank
MainLoopModeGameMainContinue
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub GameMainLoop bank11
          return otherbank
MainLoopModeWinnerAnnouncement
          rem CRITICAL: on gameMode gosub is a near call (pushes 2-byte return otherbank address)
          rem Returns: Far (return otherbank)
          rem Must use return otherbank to match the near call, not return otherbank
          gosub WinnerAnnouncementLoop bank12
          return otherbank
MainLoopContinue
          rem Routes audio updates after per-mode execution
          rem Returns: Far (return otherbank)
          rem Inputs: gameMode (global 0-7)
          rem Outputs: Falls through to MainLoopDrawScreen
          rem Mutates: None; dispatcher only
          rem Calls: PlayMusic bank1 (for modes < 3 and mode 7); colocated with MainLoop/MainLoopDrawScreen
          rem Notes: Modes 3-6 handle audio updates in their own routines

          rem Check if music update is needed for game modes < 3 or mode 7
          if gameMode < 3 then gosub PlayMusic bank15
          if gameMode = 7 then gosub PlayMusic bank15
SkipMusicUpdate
MainLoopDrawScreen
          rem Renders the appropriate screen for the current game mode
          rem Returns: Far (return otherbank)
          rem Inputs: gameMode (global 0-7)
          rem Outputs: Screen rendered via titledrawscreen or drawscreen
          rem Mutates: TIA registers, playfield, sprite state
          rem Calls: titledrawscreen bank9 (title screens); colocated with MainLoop
          rem Notes: Modes 3-6 funnel through mode-specific draw logic

          rem Titlescreen graphics and kernel reside in bank9
          if gameMode < 3 then gosub DrawTitleScreen bank9
          if gameMode >= 3 then drawscreen
          goto MainLoop bank16
