"Cart.MD5" "@@MD5@@"
"Cart.Manufacturer" "Interworldly Adventuring, LLC"
"Cart.ModelNo" "Chaos.@@TV@@"
"Cart.Name" "ChaosFight"
"Cart.Rarity" "Homebrew"
"Cart.Type" "DF"
"Cart.Url" "https://interworldly.com/games/ChaosFight"
"Controller.Left" "JOYSTICK"
"Controller.Right" "JOYSTICK"
"Display.Format" "@@TV@@"
"Display.Phosphor" "YES"
